apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-jenkins-volume
  namespace: jenkins
  annotations:
    pv.beta.kubernetes.io/gid: "0" 
spec:
  capacity:
    storage: 4Gi 
  accessModes: 
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster 
    path: jenkins-vol
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
